[2024-06-11T04:03:32.024+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T04:03:32.046+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.read_files_from_path manual__2024-06-11T04:03:31.265020+00:00 [queued]>
[2024-06-11T04:03:32.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.read_files_from_path manual__2024-06-11T04:03:31.265020+00:00 [queued]>
[2024-06-11T04:03:32.054+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T04:03:32.069+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_files_from_path> on 2024-06-11 04:03:31.265020+00:00
[2024-06-11T04:03:32.075+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=974) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T04:03:32.076+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'read_files_from_path', 'manual__2024-06-11T04:03:31.265020+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmpqbk9vgzd']
[2024-06-11T04:03:32.077+0000] {standard_task_runner.py:63} INFO - Started process 975 to run task
[2024-06-11T04:03:32.077+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask read_files_from_path
[2024-06-11T04:03:32.114+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.read_files_from_path manual__2024-06-11T04:03:31.265020+00:00 [running]> on host 678b3b027d57
[2024-06-11T04:03:32.185+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='read_files_from_path' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T04:03:31.265020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T04:03:31.265020+00:00'
[2024-06-11T04:03:32.187+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T04:03:32.211+0000] {base.py:84} INFO - Using connection ID 'invoices' for task execution.
[2024-06-11T04:03:32.240+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-11T04:03:32.242+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T04:03:32.250+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=hello_word, task_id=read_files_from_path, run_id=manual__2024-06-11T04:03:31.265020+00:00, execution_date=20240611T040331, start_date=20240611T040332, end_date=20240611T040332
[2024-06-11T04:03:32.292+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-11T04:03:32.315+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-11T04:03:32.379+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
